//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDistributorsWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_REST_TokenDetails
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string ClientID { get; set; }
        public string ClientKey { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
